name: CI/CD with Docker

on:
  push:
    branches:
      - #develop  # Ветка для запуска workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Используем Ubuntu для выполнения задач

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Шаг для клонирования репозитория

      - name: Build Docker
        run: |
          docker build -t my-docs-builder .
          docker run -d --name docs-builder my-docs-builder

      - name: Copy documentation artifacts
        run: |
          mkdir -p docs_artifacts
          docker cp docs-builder:/app/build/html docs_artifacts/

      - name: List documentation artifacts
        run: |
          ls -R docs_artifacts

      # Шаг 6: Загрузка на FTP
      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_HOST }}  # Используется секрет с адресом FTP-сервера
          username: ${{ secrets.FTP_USERNAME }}  # Используется секрет с именем пользователя
          password: ${{ secrets.FTP_PASSWORD }}  # Используется секрет с паролем
          server-dir: /techwriters.ru/ # Путь на FTP-сервере, куда загружать файлы
          local-dir: docs_artifacts/html/  # Путь к сгенерированным файлам, которые будут загружены



